name: publish-to-github-pages
on:
  push:
    branches:
      - main
      - staging

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    if: github.ref_name == 'main'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/setup-node
      - name: Create .env.production file 📝
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}" > .env.production
          echo "NEXT_PUBLIC_GA_MEASUREMENT_ID=${{ vars.NEXT_PUBLIC_GA_MEASUREMENT_ID }}" >> .env.production
        working-directory: ./code
      - name: Setup Pages ⚙️
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      - name: Build with Next.js 🏗️
        run: npx next build
        working-directory: ./code
      - name: Upload artifact 📡
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./code/out

  deploy:
    if: github.ref_name == 'main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-staging-vercel:
    if: github.ref_name == 'staging'
    environment: staging
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/setup-node
      - name: Install Vercel CLI ⚙️
        run: npm install --global vercel@latest
      - name: Deploy Staging to Vercel 🚀
        id: deploy
        run: |
          echo "url=$(vercel deploy --prod --yes \
            --build-env NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }} \
            --build-env NEXT_PUBLIC_GA_MEASUREMENT_ID=${{ vars.NEXT_PUBLIC_GA_MEASUREMENT_ID }} \
            --token=${{ vars.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT
        working-directory: ./code
      - name: Alias to Staging Domain 🔗
        run: vercel alias set ${{ steps.deploy.outputs.url }} ${{ vars.STAGING_DOMAIN }} --token=${{ vars.VERCEL_TOKEN }}
        working-directory: ./code
